# Site settings
title: theculleralexander
email: nothing@yet.com
description: >
  New site for my dearest friend.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site


# Build settings
markdown: kramdown
